# Generated by Django 5.0.6 on 2024-05-30 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_create_comment_model"),
        ("news", "0002_edit_regex_for_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="Author of the news",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="news author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="news",
            field=models.ForeignKey(
                help_text="Comment for this news",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news.news",
                verbose_name="comment for news",
            ),
        ),
    ]
