# Generated by Django 5.0.6 on 2024-05-30 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_change_related_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="Author of the comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="comment author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(
                help_text="Text of the comment",
                max_length=500,
                verbose_name="comment text",
            ),
        ),
    ]
