# Generated by Django 5.0.6 on 2024-05-31 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_change_help_text_for_author_text"),
        ("news", "0003_change_text_field_blank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="unique_comment_for_author_to_news",
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.UniqueConstraint(
                fields=("author", "text"), name="unique_comment_for_author_to_news"
            ),
        ),
    ]
