# Generated by Django 5.0.6 on 2024-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_change_constraint_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                help_text="Text of the comment",
                max_length=500,
                verbose_name="comment text",
            ),
        ),
    ]
