# Generated by Django 5.0.6 on 2024-05-30 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0001_create_like_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="date_created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date the like was created",
                verbose_name="like date created at",
            ),
            preserve_default=False,
        ),
    ]
