# Generated by Django 5.0.6 on 2024-05-30 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0002_add_date_created_at_field"),
        ("news", "0002_edit_regex_for_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="author",
            field=models.ForeignKey(
                help_text="Author of the like",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="like author",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="news",
            field=models.ForeignKey(
                help_text="News to like",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="news.news",
                verbose_name="news to like",
            ),
        ),
    ]
