# Generated by Django 5.0.6 on 2024-05-29 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date the news was created",
                        verbose_name="news date created at",
                    ),
                ),
                (
                    "date_updated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date the news was updated",
                        verbose_name="news date updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        error_messages={
                            "unique": "A news with this name already exists."
                        },
                        help_text="News name",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Zа-яА-ЯёЁ0-9.!?,_ \\-]+$"
                            )
                        ],
                        verbose_name="news title",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        help_text="Text of the news",
                        max_length=1500,
                        verbose_name="news text",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author of the news",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="news author",
                    ),
                ),
            ],
            options={
                "verbose_name": "news",
                "verbose_name_plural": "news",
                "ordering": ("-date_updated_at",),
            },
        ),
    ]
