# Generated by Django 5.0.6 on 2024-05-29 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_create_news_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-date_created_at",),
                "verbose_name": "news",
                "verbose_name_plural": "news",
            },
        ),
        migrations.RemoveField(
            model_name="news",
            name="created_at",
        ),
        migrations.AddField(
            model_name="news",
            name="date_created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date the news was created",
                verbose_name="news date created at",
            ),
            preserve_default=False,
        ),
    ]
