# Generated by Django 5.0.6 on 2024-05-29 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_change_name_of_date_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                error_messages={"unique": "A news with this name already exists."},
                help_text="News name",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("^[a-zA-Zа-яА-ЯёЁ.!?, \\-]+$")
                ],
                verbose_name="news title",
            ),
        ),
    ]
