# Generated by Django 5.0.6 on 2024-05-29 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_add_validators_to_title_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-date_updated_at",),
                "verbose_name": "news",
                "verbose_name_plural": "news",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="date_updated_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date the news was updated",
                verbose_name="news date updated at",
            ),
            preserve_default=False,
        ),
    ]
