# Generated by Django 5.0.6 on 2024-05-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_create_users_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="admin status",
            ),
        ),
    ]
